# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b45481d20e6ff120c2e7800b1d8e0d4e72bb59f5330bfdbedfff20cc5bb6d6de80eb136cab1b8465b80049e91e51c22623d55eb23ae5ce977162fad504a189bb

test:
  secret_key_base: 7cee431e09274518bf054e54a5b5270555820e13a6de3a83da0dd517a20d166bcc12144ddee727ae7fdea4900f96d14c424f74ebfab8a64bbf3ad9d465cf2e2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
